# Generated by Django 5.2.12 on 2026-06-15 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_measurementperiod_authorization_note_and_more'),
        ('catalog', '0006_cleanup_budget_item_manufacturer_hints'),
        ('stock', '0002_material_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida'), ('ADJUST_POSITIVE', 'Ajuste positivo'), ('ADJUST_NEGATIVE', 'Ajuste negativo'), ('TRANSFER', 'Transferencia'), ('MEASUREMENT_OUT', 'Saida de medicao'), ('MEASUREMENT_OUT_REVERSAL', 'Estorno de saida de medicao')], max_length=30),
        ),
        migrations.CreateModel(
            name='MeasurementMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPLIED', 'Baixado'), ('REVERSED', 'Estornado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_materials', to='stock.material')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_materials', to='billing.measurementperiod')),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_materials', to='stock.stocklocation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_stock_materials', to='catalog.unit')),
            ],
            options={
                'ordering': ['measurement_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementStockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_type', models.CharField(choices=[('OUT', 'Saida'), ('REVERSAL', 'Estorno')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consumptions', to='billing.measurementperiod')),
                ('measurement_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='stock.measurementmaterial')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_consumptions', to='stock.stockmovement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='measurementmaterial',
            index=models.Index(fields=['measurement', 'status'], name='idx_meas_mat_measure_status'),
        ),
        migrations.AddIndex(
            model_name='measurementmaterial',
            index=models.Index(fields=['material', 'stock_location'], name='idx_meas_mat_material_loc'),
        ),
        migrations.AddIndex(
            model_name='measurementstockconsumption',
            index=models.Index(fields=['measurement', 'consumption_type'], name='idx_meas_stock_cons_type'),
        ),
        migrations.AddIndex(
            model_name='measurementstockconsumption',
            index=models.Index(fields=['stock_movement'], name='idx_meas_stock_cons_mov'),
        ),
    ]
