# Generated by Django 5.2.12 on 2026-06-16 11:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockmovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='material',
            name='item_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='material',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida'), ('ADJUST_POSITIVE', 'Ajuste positivo'), ('ADJUST_NEGATIVE', 'Ajuste negativo'), ('TRANSFER', 'Transferencia'), ('ENTRADA_INICIAL', 'Entrada inicial'), ('MEASUREMENT_OUT', 'Saida de medicao'), ('MEASUREMENT_OUT_REVERSAL', 'Estorno de saida de medicao')], max_length=30),
        ),
        migrations.CreateModel(
            name='InitialStockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='stock/initial-imports/')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Pendente de conferencia'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('ERROR', 'Com erros')], default='DRAFT', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_materials_created', models.PositiveIntegerField(default=0)),
                ('total_materials_updated', models.PositiveIntegerField(default=0)),
                ('total_movements_created', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_stock_imports', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_stock_imports', to='stock.stocklocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InitialStockImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('original_code', models.CharField(blank=True, max_length=80)),
                ('original_category', models.CharField(blank=True, max_length=120)),
                ('original_subcategory', models.CharField(blank=True, max_length=120)),
                ('original_item_type', models.CharField(blank=True, max_length=120)),
                ('original_description', models.CharField(blank=True, max_length=255)),
                ('original_brand', models.CharField(blank=True, max_length=120)),
                ('original_unit', models.CharField(blank=True, max_length=40)),
                ('raw_quantity', models.CharField(blank=True, max_length=80)),
                ('original_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('confirmed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('NEW_MATERIAL', 'Novo material'), ('EXISTING_MATERIAL', 'Material existente'), ('UPDATE_MATERIAL', 'Atualizar material'), ('ERROR', 'Erro'), ('IGNORED', 'Ignorado'), ('CONFIRMED', 'Confirmado')], default='PENDING', max_length=30)),
                ('planned_action', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.initialstockimport')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_stock_import_items', to='stock.material')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_stock_import_items', to='stock.stockmovement')),
            ],
            options={
                'ordering': ['import_batch_id', 'row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_initial_stock_import_row')],
            },
        ),
    ]
