# Generated by Django 5.2.12 on 2026-06-16 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectstage'),
        ('stock', '0003_alter_stockmovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida'), ('ADJUST_POSITIVE', 'Ajuste positivo'), ('ADJUST_NEGATIVE', 'Ajuste negativo'), ('TRANSFER', 'Transferencia'), ('PURCHASE_IN', 'Entrada de compra'), ('MEASUREMENT_OUT', 'Saida de medicao'), ('MEASUREMENT_OUT_REVERSAL', 'Estorno de saida de medicao')], max_length=30),
        ),
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='stock/imports/')),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Pendente de conferencia'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('ERROR', 'Com erros')], default='DRAFT', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_imports', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_imports', to='stock.stocklocation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_imports', to='core.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('normalized_alias', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stock.material')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('normalized_alias', 'supplier'), name='uniq_material_alias_normalized_supplier')],
            },
        ),
        migrations.CreateModel(
            name='StockImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('original_code', models.CharField(blank=True, max_length=80)),
                ('supplier_code', models.CharField(blank=True, max_length=80)),
                ('original_description', models.CharField(blank=True, max_length=255)),
                ('original_unit', models.CharField(blank=True, max_length=40)),
                ('raw_quantity', models.CharField(blank=True, max_length=80)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confirmed_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PENDING_MATERIAL', 'Pendente de material'), ('PENDING_UNIT', 'Pendente de unidade'), ('PENDING_QUANTITY', 'Pendente de quantidade'), ('IGNORED', 'Ignorado'), ('CONFIRMED', 'Confirmado')], default='PENDING_MATERIAL', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('manual_adjustment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockimport')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_import_items', to='stock.material')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_import_items', to='stock.stockmovement')),
            ],
            options={
                'ordering': ['import_batch_id', 'row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'row_number'), name='uniq_stock_import_item_row')],
            },
        ),
    ]
