# Generated by Django 5.2.12 on 2026-06-29 11:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectstage'),
        ('stock', '0005_alter_stockmovement_movement_type_materialalias_stockimport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('IN_REVIEW', 'Em analise'), ('APPROVED', 'Aprovada'), ('PARTIALLY_FULFILLED', 'Parcialmente atendida'), ('FULFILLED', 'Atendida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_items_with_project_stock', models.PositiveIntegerField(default=0)),
                ('total_items_with_transfer_suggestion', models.PositiveIntegerField(default=0)),
                ('total_items_with_purchase_suggestion', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='core.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('project_available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('suggested_project_usage_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('central_available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('suggested_transfer_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('suggested_purchase_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('approved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('AVAILABLE_ON_PROJECT', 'Disponivel na obra'), ('TRANSFER_SUGGESTED', 'Transferencia sugerida'), ('PURCHASE_SUGGESTED', 'Compra sugerida'), ('MIXED', 'Misto'), ('FULFILLED', 'Atendido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='stock.material')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.materialrequest')),
            ],
            options={
                'ordering': ['request_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'material'), name='uniq_material_request_item_material'), models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='material_request_item_qty_positive')],
            },
        ),
    ]
