# Generated by Django 5.2.12 on 2026-06-29 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cleanup_budget_item_manufacturer_hints'),
        ('core', '0004_projectstage'),
        ('stock', '0006_materialrequest_materialrequestitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequestitem',
            name='transfer_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_request_transfer_items', to='stock.stockmovement'),
        ),
        migrations.AlterField(
            model_name='materialrequestitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('AVAILABLE_ON_PROJECT', 'Disponivel na obra'), ('TRANSFER_SUGGESTED', 'Transferencia sugerida'), ('PURCHASE_SUGGESTED', 'Compra sugerida'), ('MIXED', 'Misto'), ('TRANSFER_GENERATED', 'Transferencia gerada'), ('PURCHASE_GENERATED', 'Compra gerada'), ('TRANSFER_PURCHASE_GENERATED', 'Transferencia e compra geradas'), ('FULFILLED', 'Atendido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('GENERATED', 'Gerado'), ('QUOTING', 'Em cotacao'), ('PURCHASED', 'Comprado'), ('CANCELLED', 'Cancelado')], default='GENERATED', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('material_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='stock.materialrequest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='core.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('QUOTED', 'Cotado'), ('PURCHASED', 'Comprado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='stock.material')),
                ('material_request_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_item', to='stock.materialrequestitem')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.purchaserequest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='catalog.unit')),
            ],
            options={
                'ordering': ['purchase_request_id', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_request_item_qty_positive')],
            },
        ),
    ]
