# Generated by Django 5.2.12 on 2026-06-29 13:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_measurementperiod_authorization_note_and_more'),
        ('stock', '0007_materialrequestitem_transfer_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='consumed_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_stock_consumptions', to='stock.material'),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='pending_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='reversal_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_reversal_consumptions', to='stock.stockmovement'),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('PENDING_STOCK', 'Pendente de estoque'), ('PARTIAL', 'Parcial'), ('REVERSED', 'Estornado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_stock_consumptions', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='measurementstockconsumption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='measurement_stock_consumption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_item', to='stock.measurementstockconsumption'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='stock_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='stock.stockbalance'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='billing.measurementperiod'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='measurement_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.measurementmaterial'),
        ),
        migrations.AlterField(
            model_name='measurementmaterial',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPLIED', 'Baixado'), ('PARTIAL', 'Parcial'), ('PENDING_STOCK', 'Pendente de estoque'), ('REVERSED', 'Estornado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementstockconsumption',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurement_consumptions', to='stock.stockmovement'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='material_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='stock.materialrequest'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='material_request_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_item', to='stock.materialrequestitem'),
        ),
    ]
