# Generated by Django 5.2.12 on 2026-06-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_measurementstockconsumption_consumed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementstockconsumption',
            name='measurement_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='stock.measurementmaterial'),
        ),
    ]
