# Generated by Django 5.2.12 on 2026-06-30 19:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectstage'),
        ('stock', '0009_alter_measurementstockconsumption_measurement_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Estoque baixo'), ('REAL_SHORTAGE_FROM_MEASUREMENT', 'Falta real da medicao'), ('PENDING_MEASUREMENT_CONSUMPTION', 'Consumo pendente da medicao'), ('MANUAL_REVIEW', 'Revisao manual')], max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PURCHASE', 'Em compra'), ('RESOLVED', 'Resolvido'), ('DISMISSED', 'Ignorado'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('shortage_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('suggested_purchase_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alerts', to='stock.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='core.project')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_alerts', to='stock.stocklocation')),
            ],
            options={
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='stock_alert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_item', to='stock.stockalert'),
        ),
        migrations.CreateModel(
            name='StockMinimumRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimum_rules', to='stock.material')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minimum_rules', to='stock.stocklocation')),
            ],
            options={
                'ordering': ['stock_location', 'material'],
            },
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['material', 'stock_location', 'alert_type', 'status'], name='idx_stock_alert_active'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['project', 'status'], name='idx_stock_alert_project_status'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='stock_alert_current_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0)), name='stock_alert_minimum_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(('shortage_quantity__gte', 0)), name='stock_alert_shortage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_purchase_quantity__gte', 0)), name='stock_alert_suggested_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockminimumrule',
            constraint=models.UniqueConstraint(fields=('material', 'stock_location'), name='uniq_stock_min_rule_material_loc'),
        ),
        migrations.AddConstraint(
            model_name='stockminimumrule',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0)), name='stock_min_rule_quantity_non_negative'),
        ),
    ]
