# Generated by Django 5.2.12 on 2026-07-01 13:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_measurementstockconsumption_measurement_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='stock/transfer-imports/')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_REVIEW', 'Pendente de conferencia'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('ERROR', 'Com erros')], default='DRAFT', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('total_valid_items', models.PositiveIntegerField(default=0)),
                ('total_error_items', models.PositiveIntegerField(default=0)),
                ('total_transferred_items', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_imports', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_imports', to='stock.stocklocation')),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_imports', to='stock.stocklocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('original_code', models.CharField(blank=True, max_length=80)),
                ('original_description', models.CharField(blank=True, max_length=255)),
                ('original_brand', models.CharField(blank=True, max_length=120)),
                ('original_unit', models.CharField(blank=True, max_length=40)),
                ('raw_quantity', models.CharField(blank=True, max_length=80)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('confirmed_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('OK', 'OK'), ('PENDING_MATERIAL', 'Pendente de material'), ('PENDING_QUANTITY', 'Pendente de quantidade'), ('INSUFFICIENT_STOCK', 'Saldo insuficiente'), ('IGNORED', 'Ignorado'), ('CONFIRMED', 'Confirmado'), ('ERROR', 'Erro')], default='PENDING', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_import_items', to='stock.material')),
                ('transfer_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stocktransferimport')),
                ('transfer_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_import_items', to='stock.stockmovement')),
            ],
            options={
                'ordering': ['transfer_import_id', 'row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('transfer_import', 'row_number'), name='uniq_stock_transfer_import_row')],
            },
        ),
    ]
