# Generated by Django 5.2.12 on 2026-07-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stocktransferimport_stocktransferimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimport',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='total_error_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='total_movements_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='total_valid_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockimportitem',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockimportitem',
            name='original_brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stockimportitem',
            name='original_supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stockimportitem',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('PENDING_MATERIAL', 'Pendente de material'), ('PENDING_UNIT', 'Pendente de unidade'), ('PENDING_QUANTITY', 'Pendente de quantidade'), ('ERROR', 'Erro'), ('IGNORED', 'Ignorado'), ('CONFIRMED', 'Confirmado')], default='PENDING_MATERIAL', max_length=30),
        ),
    ]
