# Generated by Django 5.2.12 on 2026-03-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(default='FGV/IBRE', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_month', models.DateField()),
                ('apply_to', models.CharField(choices=[('TOTAL', 'Total'), ('MATERIAL', 'Material'), ('LABOR', 'Labor')], default='TOTAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('price_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_adjustments', to='pricing.priceindex')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='PriceIndexValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_month', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('price_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='pricing.priceindex')),
            ],
            options={
                'ordering': ['price_index_id', 'ref_month'],
                'constraints': [models.UniqueConstraint(fields=('price_index', 'ref_month'), name='uniq_price_index_ref_month')],
            },
        ),
    ]
