# Generated by Django 5.2.12 on 2026-03-06 13:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eap_code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('qty_contracted', models.DecimalField(decimal_places=3, max_digits=14)),
                ('pu_material', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('pu_labor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='core.project')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='catalog.unit')),
            ],
            options={
                'ordering': ['project_id', 'eap_code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'eap_code'), name='uniq_budget_item_project_eap')],
            },
        ),
    ]
