# Generated by Django 5.2.12 on 2026-03-06 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_seed_location_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CREATE_ONLY', 'Create only'), ('UPSERT_BY_EAP', 'Upsert by EAP'), ('REPLACE_ALL', 'Replace all')], default='UPSERT_BY_EAP', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('APPLIED', 'Applied'), ('ERROR', 'Error')], default='PREVIEW', max_length=10)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('preview_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_import_jobs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
