# Generated by Django 5.2.12 on 2026-04-10 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_budgetimportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItemAdditionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_additional_material_in', to='catalog.budgetitem')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_materials', to='catalog.budgetitem')),
            ],
            options={
                'ordering': ['parent_item_id', 'additional_item__eap_code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parent_item', 'additional_item'), name='uniq_budget_additional_material')],
            },
        ),
    ]
