# Generated by Django 5.2.12 on 2026-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_budgetitemadditionalmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='discipline',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
