# Generated by Django 5.2.12 on 2026-03-06 13:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ref_month', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent'), ('IN_REVIEW', 'In review'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('financial_status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('total_material_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_labor_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_indexed_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('index_code_snapshot', models.CharField(blank=True, max_length=30)),
                ('index_base_month_snapshot', models.DateField(blank=True, null=True)),
                ('index_ref_month_snapshot', models.DateField(blank=True, null=True)),
                ('index_factor_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_periods', to='core.project')),
            ],
            options={
                'ordering': ['project_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_kind', models.CharField(choices=[('CONTRACTED', 'Contracted'), ('EXTRA', 'Extra')], max_length=20)),
                ('extra_description', models.CharField(blank=True, max_length=255)),
                ('extra_pu_material', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('extra_pu_labor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_period', models.DecimalField(decimal_places=3, max_digits=14)),
                ('justification', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_measurement_lines', to='catalog.unit')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_lines', to='catalog.budgetitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_lines', to='core.projectlocation')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.measurementperiod')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('PIX', 'Pix'), ('TRANSFER', 'Transfer'), ('BOLETO', 'Boleto'), ('DESCONTO_BALAO', 'Desconto balao'), ('DESCONTO_PARCELA', 'Desconto parcela')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VOID', 'Void')], default='ACTIVE', max_length=10)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='billing.measurementperiod')),
            ],
            options={
                'ordering': ['period_id', 'event_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='measurementperiod',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_measurement_project_number'),
        ),
        migrations.AddIndex(
            model_name='measurementline',
            index=models.Index(fields=['period', 'item'], name='idx_measure_line_period_item'),
        ),
    ]
