# Generated by Django 5.2.12 on 2026-03-11 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementline',
            name='excess_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementline',
            name='excess_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
    ]
