# Generated by Django 5.2.12 on 2026-04-10 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_measurementline_excess_justification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=3, max_digits=14)),
                ('application_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_line_histories', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='billing.measurementline')),
            ],
            options={
                'ordering': ['-application_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['line', 'application_date'], name='idx_measure_history_line_app')],
            },
        ),
    ]
