# Generated by Django 5.2.12 on 2026-04-10 18:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_measurementlinehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementline',
            name='additional_materials_base_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='measurementline',
            name='generated_from_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_lines', to='billing.measurementline'),
        ),
        migrations.AddField(
            model_name='measurementline',
            name='is_generated_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurementline',
            name='use_additional_materials',
            field=models.BooleanField(default=False),
        ),
    ]
