# Generated by Django 5.2.12 on 2026-04-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_measurementline_additional_materials_base_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementlinehistory',
            name='is_generated_additional_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurementlinehistory',
            name='source_item_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='measurementlinehistory',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_history_entries', to='billing.measurementline'),
        ),
    ]
