# Generated by Django 5.2.12 on 2026-04-10 20:15

from decimal import Decimal

from django.db import migrations, models


def backfill_additional_materials_quantity(apps, schema_editor):
    MeasurementLine = apps.get_model("billing", "MeasurementLine")
    MeasurementLineHistory = apps.get_model("billing", "MeasurementLineHistory")

    for line in MeasurementLine.objects.all().iterator():
        remaining = line.additional_materials_base_qty or Decimal("0")
        histories = MeasurementLineHistory.objects.filter(line_id=line.id).order_by(
            "-application_date",
            "-created_at",
            "-id",
        )
        for history in histories:
            if history.is_generated_additional_entry or remaining <= 0:
                history.additional_materials_quantity = Decimal("0")
            else:
                allocated = min(history.quantity_added, remaining)
                history.additional_materials_quantity = allocated
                remaining -= allocated
            history.save(update_fields=["additional_materials_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_measurementlinehistory_is_generated_additional_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementlinehistory",
            name="additional_materials_quantity",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=14),
        ),
        migrations.RunPython(backfill_additional_materials_quantity, migrations.RunPython.noop),
    ]
