# Generated by Django 5.2.12 on 2026-04-13 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_measurementlinehistory_additional_materials_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementperiod',
            name='authorization_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='in_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurementperiod',
            name='sent_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MeasurementWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent'), ('IN_REVIEW', 'In review'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('SENT', 'Sent'), ('IN_REVIEW', 'In review'), ('AUTHORIZED', 'Authorized'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_workflow_changes', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='billing.measurementperiod')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
