# Generated by Django 5.2.12 on 2026-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_measurementperiod_authorization_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementline',
            name='application_reference',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Referencia da aplicacao'),
        ),
        migrations.AddField(
            model_name='measurementlinehistory',
            name='application_reference',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Referencia da aplicacao'),
        ),
    ]
