# Generated by Django 5.2.12 on 2026-07-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_measurementline_application_reference_and_more'),
        ('catalog', '0006_cleanup_budget_item_manufacturer_hints'),
        ('core', '0004_projectstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_environments', to='core.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PredefinedEnvironmentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predefined_environment_disciplines', to='catalog.discipline')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='billing.predefinedenvironment')),
            ],
            options={
                'ordering': ['environment_id', 'discipline__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PredefinedEnvironmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='billing.predefinedenvironmentdiscipline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predefined_environment_materials', to='catalog.budgetitem')),
            ],
            options={
                'ordering': ['environment_discipline_id', 'order_index', 'item__eap_code', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='predefinedenvironment',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_predef_env_project_name'),
        ),
        migrations.AddConstraint(
            model_name='predefinedenvironmentdiscipline',
            constraint=models.UniqueConstraint(fields=('environment', 'discipline'), name='uniq_predef_env_discipline'),
        ),
        migrations.AddConstraint(
            model_name='predefinedenvironmentmaterial',
            constraint=models.UniqueConstraint(fields=('environment_discipline', 'item'), name='uniq_predef_env_material_item'),
        ),
    ]
