# Generated by Django 5.2.12 on 2026-03-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('SIENGE_MASTER', 'Sienge master'), ('SIENGE_SNAPSHOT', 'Sienge snapshot'), ('DOCX_TIMBRADO', 'Docx timbrado')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('ERROR', 'Error')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='billing.measurementperiod')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.project')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
