# Generated by Django 5.2.12 on 2026-03-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementexport',
            name='export_type',
            field=models.CharField(choices=[('SIENGE_MASTER', 'Sienge master'), ('SIENGE_SNAPSHOT', 'Sienge snapshot'), ('DOCX_TIMBRADO', 'Docx timbrado'), ('PDF_TIMBRADO', 'Pdf timbrado')], max_length=20),
        ),
    ]
