# Generated by Django 5.2.12 on 2026-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_measurementexport_export_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementexport',
            name='export_type',
            field=models.CharField(choices=[('SIENGE_MASTER', 'Sienge master'), ('SIENGE_SNAPSHOT', 'Sienge snapshot'), ('DOCX_TIMBRADO', 'Docx timbrado'), ('PDF_TIMBRADO', 'Pdf timbrado'), ('XLSX_BOLETIM', 'Xlsx boletim')], max_length=20),
        ),
    ]
