# Generated by Django 5.2.12 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0003_alter_measurementexport_export_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementexport",
            name="summary_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
