# Generated by Django 5.2.12 on 2026-04-13 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_discipline_model_and_budgetitem_fk'),
        ('core', '0003_project_location_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('responsible_name', models.CharField(max_length=255)),
                ('weather_morning', models.CharField(blank=True, choices=[('CLEAR', 'Limpo'), ('CLOUDY', 'Nublado'), ('RAINY', 'Chuvoso'), ('WINDY', 'Vento'), ('STOPPED', 'Paralisado')], max_length=20)),
                ('weather_afternoon', models.CharField(blank=True, choices=[('CLEAR', 'Limpo'), ('CLOUDY', 'Nublado'), ('RAINY', 'Chuvoso'), ('WINDY', 'Vento'), ('STOPPED', 'Paralisado')], max_length=20)),
                ('weather_night', models.CharField(blank=True, choices=[('CLEAR', 'Limpo'), ('CLOUDY', 'Nublado'), ('RAINY', 'Chuvoso'), ('WINDY', 'Vento'), ('STOPPED', 'Paralisado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('general_observation', models.TextField(blank=True)),
                ('interruption_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_logs', to='core.project')),
            ],
            options={
                'ordering': ['-log_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_activities', to='catalog.discipline')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_activities', to='core.projectlocation')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_entries', to='rdo.dailyworklog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_type', models.CharField(choices=[('ORIENTACAO', 'Orientacao'), ('ACIDENTE', 'Acidente'), ('INTERRUPCAO', 'Interrupcao'), ('VISITA', 'Visita'), ('INSPECAO', 'Inspecao'), ('OUTRO', 'Outro')], max_length=20)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='rdo.dailyworklog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkTeamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('role_or_service', models.CharField(blank=True, max_length=255)),
                ('worker_count', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='rdo.dailyworklog')),
            ],
            options={
                'ordering': ['team_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_number', models.CharField(blank=True, max_length=80)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('contractor_document', models.CharField(blank=True, max_length=32)),
                ('technical_manager_name', models.CharField(blank=True, max_length=255)),
                ('technical_manager_crea', models.CharField(blank=True, max_length=80)),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('address_snapshot', models.CharField(blank=True, max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=80)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_info', to='core.project')),
            ],
            options={
                'ordering': ['project__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyworklog',
            constraint=models.UniqueConstraint(fields=('project', 'log_date'), name='uniq_daily_work_log_project_date'),
        ),
    ]
