# Generated by Django 5.2.12 on 2026-04-14 13:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_discipline_model_and_budgetitem_fk'),
        ('core', '0003_project_location_template'),
        ('rdo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkoccurrence',
            name='occurrence_type',
            field=models.CharField(choices=[('ORIENTACAO', 'Orientação'), ('ACIDENTE', 'Acidente'), ('INTERRUPCAO', 'Interrupção'), ('VISITA', 'Visita'), ('INSPECAO', 'Inspeção'), ('OUTRO', 'Outro')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyWorkMaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_snapshot', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_snapshot', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_entries', to='rdo.dailyworklog')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_material_entries', to='catalog.budgetitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_material_entries', to='core.projectlocation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
