# Generated by Django 5.2.12 on 2026-04-14 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_role_or_service_to_activity_description(apps, schema_editor):
    DailyWorkTeamEntry = apps.get_model("rdo", "DailyWorkTeamEntry")
    for entry in DailyWorkTeamEntry.objects.all().iterator():
        entry.activity_description = entry.role_or_service or ""
        entry.save(update_fields=["activity_description"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_location_template'),
        ('rdo', '0002_alter_dailyworkoccurrence_occurrence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkteamentry',
            name='activity_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dailyworkteamentry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_team_entries', to='core.projectlocation'),
        ),
        migrations.RunPython(copy_role_or_service_to_activity_description, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dailyworkteamentry',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='dailyworkteamentry',
            name='role_or_service',
        ),
        migrations.AlterField(
            model_name='dailyworkteamentry',
            name='worker_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
