# Generated by Django 5.2.12 on 2026-03-06 13:58

from django.db import migrations


def seed_location_templates(apps, schema_editor):
    LocationTemplate = apps.get_model("core", "LocationTemplate")
    LocationTemplateItem = apps.get_model("core", "LocationTemplateItem")

    templates = [
        (
            "Prédio residencial (Palatium)",
            [
                ("SS1", "Subsolo 1", 1),
                ("TER", "Terreo", 2),
                ("HAL", "Hall", 3),
                ("LAZ", "Lazer", 4),
                ("1TP", "1 Tipo", 5),
                ("TIPO", "Tipo", 6),
                ("COB", "Cobertura", 7),
                ("EV", "Elevadores", 8),
                ("GR", "Garagem", 9),
            ],
        ),
        (
            "Obra simples",
            [
                ("GERAL", "Geral", 1),
            ],
        ),
    ]

    for template_name, items in templates:
        template, _ = LocationTemplate.objects.get_or_create(name=template_name)
        for code, name, order_index in items:
            LocationTemplateItem.objects.get_or_create(
                template=template,
                code=code,
                defaults={"name": name, "order_index": order_index},
            )


def unseed_location_templates(apps, schema_editor):
    LocationTemplate = apps.get_model("core", "LocationTemplate")
    LocationTemplate.objects.filter(
        name__in=["Prédio residencial (Palatium)", "Obra simples"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_location_templates, unseed_location_templates),
    ]
