# Generated by Django 5.2.12 on 2026-04-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_location_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="location_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.locationtemplate",
            ),
        ),
    ]
