# Generated by Django 5.2.12 on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_location_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("order_index", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "order_index", "code"],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "code"), name="uniq_project_stage_code"),
                ],
            },
        ),
    ]
